### ISSUE TITLE
request.auth.isAuthenticated always false with hapi 13.4.1?

### ISSUE THREAD

**Issue by geuis** [mtharrison/hapi-context-credentials#3]
Has this been tested with the lastest version of hapi? I'm setting up a new project with the latest version and the `onPreResponse` passes in `request.auth.isAuthenticated`, but its always false unless the route has some form of `auth` enabled on it.

**Comment by mtharrison** [comment]
That's the expected behaviour, what were you expecting?

**Comment by geuis** [comment]
When I used `hapi-context-credentials` about a year ago for another project with an earlier version of hapi, it was specifically so that once a user was authenticated the plugin would add that all route contexts. I mean, that is literally the the hapi issue that you reference in the readme for this plugin. https://github.com/hapijs/hapi/issues/2419

**Comment by mtharrison** [comment]
Yes, that's how it works.

> once a user was authenticated

By the above do you mean per-route? Or, if a user was authenticated once it remembers for other routes? If you mean the latter, it never worked that way. HTTP is a stateless protocol, hapi doesn't remember your previous requests, you have to authenticate every single request - even if it's just a browser passing a cookie automatically.

**Comment by geuis** [comment]
I think something is getting lost in the translation here. No credentials are being copied to `request.auth.credentials` and `request.auth.isAuthenticated` shows as false. Here's a snippet of my configuration.

```
// app.js
server.register([HapiAuthCookie, HapiContextCredentials], err => {
  if (err) {
    throw err;
  }

  server.auth.strategy('session', 'cookie', {
    password: process.env.cookiePwd,
    cookie: 'sess',
    clearInvalid: true,
    isSecure: process.env.NODE_ENV === 'development' ? false : true,
    ttl: 86400000, // milliseconds a day
    redirectTo: '/signin',
    validateFunc: (request, session, callback) => {
      server.app.cache.get(session.sid, (err, cached) => {
        if (err) {
          return callback(err, false);
        }

        if (!cached) {
          return callback(null, false);
        }

        return callback(null, true, cached.account);
      });
    }
  });
});
```

```
// routes.js

const routes = {
  'home': {
    path: '/',
    method: 'GET',
    handler: Controllers.Home
  },
  'signin': {
    path: '/signin',
    method: ['GET', 'POST'],
    handler: Controllers.Signin
}
```

The effect I am trying to replicate here from the earlier project is that `http://localhost/` should be accessible whether the user is signed in or not. When the user is authenticated, then we should be able to see that in `request.auth` the user is signed in.

**Comment by mtharrison** [comment]
If you want a route where auth is tested but not required, you probably want the `try` mode.

If you still think there's something wrong with this plugin, can you please create a small, yet complete example that I can run to test it. The above snippet doesn't give me enough info.
